package scanners.keycloak_security.config

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(KeycloakConnectionProperties::class)
open class KeycloakAdminClientConfig
