version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak-test
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpass
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    ports:
      - "8180:8080"
      - "9000:9000"
    command: start-dev
