version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak-test
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpass
    ports:
      - "8180:8080"
    command: start-dev
